public final class er {
   public int aaa;
   public int aba;
   public byte aca;
   public short ada = -1;
   public static int aea;
   public static String afa;
   public static String aga;
   public static String aha;
   public static String aia;
   public static String aja;
   public static String aka;
   public static String ala;
   public static String ama;
   public static String ana;
   public static String aoa;
   public static String apa;
   public static String aqa;
   public static String ara;
   public static String asa;
   public static String ata;
   public static String aua;
   public static String ava;
   public static String awa;
   public static String axa;
   public static String aya;
   public static String aza;
   public static String baa;
   public static String bba;
   public static String[] bca;
   public static String bda;
   public static String bea;
   public static String bfa;
   public static String bga;
   public static String bha;
   public static String bia;
   public static String bja;
   public static String[] bka;
   public static String bla;
   public static String bma;
   public static String bna;
   public static String boa;
   public static String bpa;
   public static String bqa;
   public static String bra;
   public static String bsa;
   public static String bta;
   public static String bua;
   public static String bva;
   public static String bwa;
   public static String bxa;
   public static String bya;
   public static String bza;
   public static String caa;
   public static String cba;
   public static String cca;
   public static String cda;
   public static String cea;
   public static String cfa;
   public static String cga;
   public static String cha;
   public static String cia;
   public static String cja;
   public static String cka;
   public static String cla;
   public static String cma;
   public static String cna;
   public static String coa;
   public static String cpa;
   public static String cqa;
   public static String cra;
   public static String csa;
   public static String cta;
   public static String cua;
   public static String cva;
   public static String cwa;
   public static String cxa;
   public static String cya;
   public static String cza;
   public static String daa;
   public static String dba;
   public static String dca;
   public static String dda;
   public static String dea;
   public static String dfa;
   public static String dga;
   public static String dha;
   public static String dia;
   public static String dja;
   public static String dka;
   public static String dla;
   public static String dma;
   public static String dna;
   public static String doa;
   public static String dpa;
   public static String dqa;
   public static String dra;
   public static String dsa;
   public static String dta;
   public static String dua;
   public static String dva;
   public static String[] dwa;
   public static String dxa;
   public static String dya;
   public static String dza;
   public static String[] eaa;
   public static String eba;
   public static String eca;
   public static String eda;
   public static String eea;
   public static String efa;
   public static String ega;
   public static String eha;
   public static String eia;
   public static String eja;
   public static String eka;
   public static String ela;
   public static String ema;
   public static String ena;
   public static String eoa;
   public static String epa;
   public static String eqa;
   public static String era;
   public static String esa;
   public static String eta;
   public static String eua;
   public static String eva;
   public static String ewa;
   public static String exa;
   public static String eya;
   public static String eza;
   public static String faa;
   public static String fba;
   public static String fca;
   public static String fda;
   public static String fea;
   public static String ffa;
   public static String fga;
   public static String fha;
   public static String fia;
   public static String fja;
   public static String fka;
   public static String fla;
   public static String fma;
   public static String fna;
   public static String foa;
   public static String fpa;
   public static String fqa;
   public static String fra;
   public static String fsa;
   public static String fta;
   public static String fua;
   public static String[] fva;
   public static String fwa;
   public static String fxa;
   public static String fya;
   public static String fza;
   public static String gaa;
   public static String gba;
   public static String gca;
   public static String gda;
   public static String gea;
   public static String gfa;
   public static String gga;
   public static String gha;
   public static String[] gia;
   public static String[] gja;
   public static String[][] gka;
   public static String[] gla;
   public static String[] gma;
   public static String[] gna;
   public static String[] goa;
   public static String[] gpa;
   public static String[] gqa;
   public static String[] gra;
   public static String[] gsa;
   public static String[] gta;
   public static String[] gua;
   public static String[] gva;
   public static String[] gwa;
   public static String[] gxa;
   public static String[] gya;
   public static String[] gza;
   public static String[] haa;
   public static String[] hba;
   public static String[] hca;
   public static String[] hda;
   public static String[] hea;
   public static String[] hfa;
   public static String[] hga;
   public static String[] hha;
   public static String[] hia;
   public static String[] hja;
   public static String[] hka;
   public static String[] hla;
   public static String[] hma;
   public static String[] hna;
   public static String[] hoa;
   public static String[] hpa;
   public static String[] hqa;
   public static String[] hra;
   public static String[] hsa;
   public static String[] hta;
   public static String[] hua;
   public static String hva;
   public static String hwa;
   public static String hxa;
   public static String hya;
   public static String hza;
   public static String iaa;
   public static String iba;
   public static String ica;
   public static String ida;
   public static String iea;
   public static String ifa;
   public static String iga;
   public static String iha;
   public static String iia;
   public static String ija;
   public static String ika;
   public static String ila;
   public static String ima;
   public static String ina;
   public static String ioa;
   public static String ipa;
   public static String iqa;
   public static String ira;
   public static String isa;
   public static String ita;
   public static String iua;
   public static String iva;
   public static String iwa;
   public static String ixa;
   public static String iya;
   public static String[] iza;
   public static String jaa;
   public static String jba;
   public static String jca;
   public static String jda;
   public static String jea;
   public static String jfa;
   public static String jga;
   public static String jha;
   public static String[] jia;
   public static String jja;
   public static String jka;
   public static String jla;
   public static String jma;
   public static String jna;
   public static String joa;
   public static String[] jpa;
   public static String[] jqa;
   public static String[] jra;
   public static String jsa;
   public static String[] jta;
   public static String[] jua;
   public static String[] jva;
   public static String[] jwa;
   public static String[] jxa;
   public static String jya;
   public static String jza;
   public static String kaa;
   public static String kba;
   public static String[] kca;
   public static String kda;
   public static String kea;
   public static String kfa;
   public static String kga;
   public static String kha;
   public static String kia;
   public static String kja;
   public static String kka;
   public static String kla;
   public static String kma;
   public static String kna;
   public static String koa;
   public static String kpa;
   public static String kqa;
   public static String kra;
   public static String ksa;
   public static String kta;
   public static String kua;
   public static String kva;
   public static String kwa;
   public static String kxa;
   public static String kya;
   public static String kza;
   public static String laa;
   public static String lba;
   public static String lca;
   public static String lda;
   public static String lea;
   public static String lfa;
   public static String lga;
   public static String lha;
   public static String lia;
   public static String lja;
   public static String lka;
   public static String[][] lla;
   public static String[] lma;
   public static String[] lna;
   public static String loa;
   public static String lpa;
   public static String lqa;
   public static String lra;
   public static String lsa;
   public static String lta;
   public static String lua;
   public static String[] lva;
   public static String[] lwa;
   public static String lxa;
   public static String lya;
   public static String lza;
   public static String maa;
   public static String mba;
   public static String mca;
   public static String mda;
   public static String mea;
   public static String mfa;
   public static String mga;
   public static String mha;
   public static String mia;
   public static String mja;
   public static String mka;
   public static String mla;
   public static String mma;
   public static String mna;
   public static String moa;
   public static String mpa;
   public static String mqa;
   public static String mra;
   public static String msa;
   public static String mta;
   public static String mua;
   public static String mva;
   public static String mwa;
   public static String mxa;
   public static String mya;
   public static String mza;
   public static String naa;
   public static String nba;
   public static String nca;
   public static String nda;
   public static String[] nea;
   public static String nfa;
   public static String nga;
   public static String nha;
   public static String nia;
   public static String nja;
   public static String[] nka;
   public static String[] nla;
   public static String[] nma;
   public static String nna;
   public static String noa;
   public static String[][] npa;
   public static String[] nqa;
   public static String[] nra;
   public static String[] nsa;
   public static String[] nta;
   public static String nua;
   public static String nva;
   public static String nwa;
   public static String nxa;
   public static String nya;
   public static String nza;
   public static String oaa;
   public static String oba;
   public static String oca;
   public static String oda;
   public static String[] oea;
   public static String ofa;
   public static String[] oga;
   public static String[] oha;
   public static String oia;
   public static String oja;
   public static String oka;
   public static String ola;
   public static String oma;
   public static String ona;
   public static String ooa;
   public static String opa;
   public static String oqa;
   public static String ora;
   public static String osa;
   public static String[] ota;
   public static String[] oua;
   public static String[] ova;
   public static String[] owa;
   public static String[] oxa;
   public static String[] oya;
   public static String oza;
   public static String[] paa;
   public static String pba;
   public static String pca;
   public static String pda;
   public static String pea;
   public static String pfa;
   public static String pga;
   public static String[] pha;
   public static String[] pia;
   public static String[] pja;
   public static String pka;
   public static String[] pla;
   public static String[] pma;
   public static String[] pna;
   public static String[] poa;
   public static String ppa;
   public static String pqa;
   public static String pra;
   public static String psa;
   public static String pta;
   public static String pua;
   public static String pva;
   public static String pwa;
   public static String pxa;
   public static String pya;
   public static String pza;
   public static String qaa;
   public static String qba;
   public static String qca;
   public static String qda;
   public static String qea;
   public static String qfa;
   public static String qga;
   public static String qha;
   public static String qia;
   public static String qja;
   public static String qka;
   public static String qla;
   public static String qma;
   public static String qna;
   public static String qoa;
   public static String qpa;
   public static String qqa;
   public static String qra;
   public static String qsa;
   public static String qta;
   public static String qua;
   public static String[] qva;
   public static String qwa;
   public static String qxa;
   public static String qya;
   public static String qza;
   public static String raa;
   public static String rba;
   public static String rca;
   public static String rda;
   public static String rea;
   public static String rfa;
   public static String rga;
   public static String rha;
   public static String ria;
   public static String rja;
   public static String rka;
   public static String rla;
   public static String rma;
   public static String rna;
   public static String roa;
   public static String rpa;
   public static String[] rqa;
   public static String rra;
   public static String rsa;
   public static String rta;
   public static String rua;
   public static String rva;
   public static String rwa;
   public static String rxa;
   public static String rya;
   public static String rza;
   public static String saa;
   public static String[][] sba;
   public static String[] sca;
   public static String sda;
   public static String sea;
   public static String sfa;
   public static String sga;
   public static String[] sha;
   public static String[] sia;
   public static String sja;
   public static String ska;
   public static String sla;
   public static String[] sma;
   public static String sna;
   public static String soa;
   public static String spa;
   public static String sqa;
   public static String sra;
   public static String ssa;
   public static String sta;
   public static String sua;
   public static String sva;
   public static String swa;
   public static String sxa;
   public static String sya;
   public static String sza;
   public static String taa;
   public static String tba;
   public static String tca;
   public static String[] tda;
   public static String tea;
   public static String tfa;
   public static String tga;
   public static String tha;
   public static String tia;
   public static String tja;
   public static String tka;
   public static String[] tla;
   public static String tma;
   public static String tna;

   public er(int var1, int var2) {
      this.aaa = var1;
      this.aba = var2;
   }

   public er(int var1, int var2, int var3) {
      this.aaa = var1;
      this.aba = var2;
      this.aca = (byte)var3;
   }

   public er() {
   }

   public static void aaa() {
      String[] var10000;
      if (aea == 0) {
         aga = "Viên ngọc này không thể gọt.";
         afa = "Viên ngọc đã đạt cấp độ tối đa.";
         aha = "Đăng ký một tài khoản sẽ giúp nhân vật đang chơi của bạn còn mãi. Bạn có muốn đăng ký không?";
         aia = "Nhiệm vụ bí ẩn";
         aja = "- Nâng hiếu chiến lên 1.";
         aka = "- Hoàn thành hang động 1 lần.";
         ala = "- Hoàn thành tà thú 1 lần.";
         ama = "- Hoàn thành 1 lần nâng cấp.";
         ana = "- Hoàn thành 10 nhiệm vụ hàng ngày.";
         aoa = "- Lấy 1000 điểm chiến trường.";
         apa = "- Hoàn thành 1 lần thất thú ải.";
         aqa = "- Hoàn thành 3 lần quay số.";
         var10000 = new String[]{"Katana", "Bokken", "Shuriken", "Tessen", "Kunai", "Liên Server"};
         ata = "Tỉ lệ thắng";
         aua = "Bạn đã tham gia: ";
         ava = "Số người tham gia: ";
         awa = "Vòng xoay may mắn";
         axa = "Tham gia";
         tka = "Tiếp tục";
         tfa = "Tài khoản của bạn chưa được xác thực. Nếu bạn xóa trò chơi, hoặc đăng nhập tài khoản khác, nhân vật đang chơi của bạn sẽ mất vĩnh viễn.";
         tga = "Chơi mới";
         tha = "Chơi tiếp";
         tia = "Đổi tài khoản";
         tja = "Máy Chủ: ";
         aya = "hạng";
         aza = "Thách Đấu";
         baa = "Thông tin";
         bca = new String[]{"Bạn có thể nhấn giữ nút chuyển mục tiêu để hiển thị danh sách người chơi khác trong map", "Đối với máy có bàn phím, bạn có thể gán phím tắt cho các phím 7,8,9 hoặc Q,W,E để sử dụng kỹ năng", "Cừu sát sẽ làm tăng 2 điểm hiếu chiến. Đồ sát sẽ làm tăng 1 điểm hiếu chiến", "Đối với Kiếm, Kunai, Đao: Nên tăng Sức Mạnh, Thể Lực, Thân pháp", "Đối với Cung, Phi Tiêu, Quạt: Nên tăng Chakra, Thể Lực, Thân pháp", "Lập tổ đội đi luyện cùng nhau bạn sẽ nhận được nhiều kinh nghiệm hơn và làm nhiệm vụ nhanh hơn", "Để giảm hiếu chiến, bạn phải bị người khác đánh trọng thương. Vào đấu trường để thi đấu để giảm", "Khi tách đá khỏi trang bị, bạn sẽ thu lại một nửa số đá ép vào lúc đầu", "Bạn có thể đổi Xu từ Yên, với điều kiện có đủ điểm hoạt động", "Bạn sẽ có phần thưởng nếu đạt thành tích cao nhất trong đấu trường mỗi ngày", "Để vào khu vực đấu trường, hãy tìm Rikudou đứng ở mỗi trường", "Bạn có thể tăng tỉ lệ thành công khi nâng cấp đồ bằng cách chọn phương pháp Cẩn Thận, nhưng sẽ tốn Lượng", "Bạn được tặng 10 lượng khi đạt cấp độ 20 tại NPC Okanechan", "Tiền Lượng được chia sẻ cho 3 nhân vật trong 1 tài khoản"};
         bba = "Quy định";
         bda = "ninjaschool";
         bea = "Chờ";
         bfa = "Menu";
         bga = "Cần";
         bha = "Di chuyển tới";
         bia = "Ngôn ngữ";
         bja = "Xóa bộ nhớ tạm";
         bka = new String[]{"Tiếng việt", "English"};
         var10000 = new String[]{"ភាសាខ្មែរ", "ភាសាអង់គ្លេស"};
         bla = "Bạn có muốn thoát game để chọn lại ngôn ngữ không ?";
         bma = "Đóng";
         bna = "Ẩn";
         boa = "Tự đánh";
         bpa = "Đứng yên";
         bqa = "do";
         bra = "Khóa";
         bsa = "Mở khóa";
         bta = "Số seri";
         bua = "Mã thẻ";
         bva = "Bật";
         bwa = "Tắt";
         bxa = "Mở link";
         bya = "Nạp";
         bza = "Kích hoạt";
         caa = "Cấu hình";
         cba = "Xóa";
         cca = "Xem";
         cda = "Tiếp tục";
         cea = "Mã rương";
         cfa = "Thẻ cào";
         cga = "Tiếp";
         cha = "Sử dụng";
         cia = "Sắp xếp";
         cja = "Bỏ ra đất";
         cka = "Tách";
         cla = "Trang bị đã được tách, bạn nhận được ";
         cma = "Có";
         cna = "Lấy ra";
         coa = "Bỏ ra";
         cpa = "Rút xu";
         cqa = "Cất xu";
         cra = "Chuyển xu";
         csa = "Cất vào";
         cta = "Bán";
         cua = "Bán nhiều";
         cva = "Bán hết";
         cwa = "Giá";
         cxa = "Mua";
         cya = "Mua nhiều";
         cza = "Không";
         daa = "Thoát";
         dba = "Chat";
         dca = "OK";
         dda = "Tài khoản";
         dea = "Mật khẩu";
         dfa = "Nhập lại";
         dga = "TK";
         dha = "MK";
         dia = "lại";
         dja = "Xin khởi động lại game.";
         dka = "Nhập lại mật khẩu";
         dla = "Nhớ";
         dma = "Bỏ";
         dna = "Đăng ký";
         doa = "Tăng đồ họa (cho máy mạnh)";
         dpa = "Giảm đồ họa (cho máy yếu)";
         dqa = "Bạn chưa nhập tên tài khoản";
         dra = "Tài khoản không được có ký tự đặt biệt.";
         dsa = "Bạn chưa nhập mật khẩu lần một.";
         dta = "Bạn chưa nhập mật khẩu lần hai.";
         dua = "Tên tài khoản phải nhiều hơn 5 ký tự";
         dva = "Mật khẩu không chính xác.";
         dwa = new String[]{"Để xác thực với tên", "bạn phải đồng ý với quy định của trò chơi."};
         dxa = "Bạn đang sử dụng mạng gì? (Bạn có thể chọn lại từ Menu)";
         dya = "Có phải bạn dùng số điện thoại đăng ký không ?";
         dza = "tin nhắn riêng";
         eaa = new String[]{"Tin nhắn gia tộc, nhóm", "Tin nhắn gia tộc", "Tin nhắn nhóm"};
         eba = "hộ tống";
         eca = "Cộng";
         eda = "Cộng nhiều";
         eea = "điểm tiềm năng";
         efa = "điểm kỹ năng";
         ega = "Đồng ý";
         eha = "Hủy";
         eia = "Danh sách";
         eja = "Thời gian";
         eka = "Thành tích";
         ela = "Tối đa";
         ema = "Tích lũy";
         ena = "Đang kết nối";
         eoa = "Đang đăng ký";
         epa = "Đang đăng nhập";
         eqa = "Chưa hoàn thành";
         era = "Thời gian hoàn thành";
         esa = "Tinh thần đồng đội";
         eta = "Chọn";
         eua = "Bỏ chọn";
         eva = "Chọn vật phẩm để xem thông tin.";
         ewa = "Gán";
         exa = "Kết quả";
         eya = "Đánh giá";
         eza = "Cấp";
         faa = "cấp";
         fba = "Bạn có muốn thoát không?";
         fca = "Nhân vật cần đổi tên";
         fda = "Máy chủ này đang bảo trì hoặc quá tải. Vui lòng thử lại sau hoặc chọn máy chủ khác.";
         fea = "Tạo mới";
         ffa = "Tên nhân vật";
         fga = "Tên nhân vật muốn kết bạn";
         fha = "đã trở thành hảo hữu.";
         fia = "Đang tải... ";
         fja = "Đóng";
         fka = "Nhận thưởng";
         fla = "rương hang động";
         fma = "Hành trang đã được mở rộng";
         fna = "Khoảng cách hộ tống quá xa, nhiệm vụ đã thất bại";
         foa = "Người được hộ tống đã trọng thương, nhiệm vụ đã thất bại";
         fpa = "vĩnh viễn";
         fqa = "Chưa nâng cấp";
         fra = "Không thể nâng cấp";
         fsa = "Dùng vật phẩm đặc biệt để nâng cấp";
         fta = "Luyện";
         fua = "Luyện đá thành công, bạn nhận được";
         fva = new String[]{"Chỉ được chuyển hóa trang bị cùng", "loại và cùng cấp trở lên.", "Sẽ khóa trang bị sau khi chuyển hóa."};
         fwa = "thất bại, bạn nhận được";
         fxa = "Đã gửi tin nhắn, xin chờ tin nhắn xác nhận.";
         fya = "Không thể gởi tin nhắn. Xin kiểm tra tiền và thử khởi động lại game.";
         fza = "Xu đang gửi";
         gaa = "Bắt đầu";
         gba = "Chọn 2 viên đá trở lên";
         gca = "Chọn Trang Bị cần tách Đá";
         gda = "Chọn Vật Phẩm và Xu trao đổi";
         gea = "Sang Hành Trang để chọn";
         gfa = "Đổi";
         gga = "ô";
         gha = "ô thứ";
         gia = new String[]{"Phím Q", "Phím W", "Phím E"};
         gja = new String[]{"Phím 7", "Phím 8", "Phím 9"};
         gka = new String[][]{{"ngắn", "cài trâm", "búi", "xù"}, {"đeo băng", "bó xù", "samurai", "nhím"}};
         gla = new String[]{"Hành trang", "Kỹ năng", "Tiềm năng", "Thông tin", "Trang bị", "Thú Cưỡi"};
         gma = new String[]{"Tiệm Y Phục", "Hành trang"};
         gna = new String[]{"Nón", "Hành trang"};
         goa = new String[]{"Áo", "Hành trang"};
         gpa = new String[]{"Găng tay", "Hành trang"};
         gqa = new String[]{"Quần", "Hành trang"};
         gra = new String[]{"Giày", "Hành trang"};
         gsa = new String[]{"Dây chuyền", "Hành trang"};
         gta = new String[]{"Nhẫn", "Hành trang"};
         gua = new String[]{"Ngọc bội", "Hành trang"};
         gva = new String[]{"Bùa", "Hành trang"};
         gwa = new String[]{"Binh khí", "Hành trang"};
         gxa = new String[]{"Dược phẩm", "Hành trang"};
         gya = new String[]{"Dược phẩm", "Hành trang"};
         gza = new String[]{"Thức ăn", "Hành trang"};
         haa = new String[]{"Thức ăn", "Hành trang"};
         hba = new String[]{"Nâng cấp", "Hành trang"};
         hca = new String[]{"Gian hàng", "Hành trang"};
         hda = new String[]{"Chuyển hóa", "Hành trang"};
         hea = new String[]{"Luyện đá", "Hành trang"};
         hfa = new String[]{"Rương đồ", "Hành trang"};
         hga = new String[]{"Cửa hàng", "Quầy sách", "Thời trang", "Gia Tộc"};
         hha = new String[]{"Bảo vật"};
         hia = new String[]{"Tách Đá", "Hành trang"};
         hja = new String[]{"Giao dịch", "Hành trang"};
         hka = new String[]{"Luyện thạch", "Hành trang"};
         hla = new String[]{"Dịch chuyển", "Hành trang"};
         hma = new String[]{"Tinh luyện", "Hành trang"};
         hna = new String[]{"Khảm ngọc", "Hành trang"};
         hoa = new String[]{"Luyện ngọc", "Hành trang"};
         hqa = new String[]{"Gọt ngọc", "Hành trang"};
         hpa = new String[]{"Giao đồ", "Hành trang"};
         hra = new String[]{"Tháo ngọc", "Hành trang"};
         tla = new String[]{"Nhặt đồ", "Hành trang"};
         var10000 = new String[]{"Del đồ", "Hành trang"};
         tma = "Xóa";
         tna = "Thêm";
         ara = "Ta sẽ làm giảm đi chỉ số bất lợi trên viên ngọc này.";
         asa = "Ta sẽ giúp ngươi tháo bỏ ngọc khảm trên trang bị.";
         hsa = new String[]{"- Sử dụng Yên, nếu không đủ dùng Xu", "- Qua trang Hành Trang để chọn Đá", "- Số lượng đá từ 2 đến 24"};
         hta = new String[]{"- Sử dụng Yên, nếu không đủ dùng Xu", "- Nâng cấp cẩn thận cần dùng lượng", "- Chỉ chọn Trang Bị và Đá", "Trang bị đã được nâng cấp tối đa"};
         hua = new String[]{"- Sử dụng Yên, nếu không đủ dùng Xu", "- Chỉ chọn Trang Bị và Ngọc"};
         hva = "Khóa G.Dịch";
         hwa = "- Luyện thành Đá cấp";
         hxa = "- Cần: # yên";
         hya = "- Cần: # lượng";
         hza = "- Cần: # xu";
         iaa = "- Xác xuất thành công";
         iba = "(thành công ";
         ica = "Cộng";
         iea = "Đã khóa";
         ifa = "Tiêu diệt";
         iga = "Bắt tà thú";
         iha = "Tiêu diệt tinh anh";
         iia = "Tiêu diệt thủ lĩnh";
         ija = "Hộ tống trẻ lạc";
         ika = "Không khóa";
         ila = "Hạn sử dụng";
         ima = "Giá bán: # yên";
         ina = "Giá mua: # xu";
         ioa = "Giá mua: # xu gia tộc";
         ipa = "Giá mua: # yên";
         iqa = "Giá mua: # lượng";
         ira = "lượng";
         isa = "Chưa có";
         ita = "Cấp kế: cấp #";
         iua = "Cấp hiện tại: cấp #";
         iva = "Cấp tối đa";
         iwa = "Đã đạt cấp độ tối đa";
         ixa = "Yêu cầu: trình độ cấp";
         iya = "Lớp: ";
         iza = new String[]{"Chính tuyến", "Phụ tuyến"};
         jaa = "Nhiệm vụ";
         jba = "Nhận NV ở";
         jca = "Bạch giả";
         jda = "Hắc giả";
         jea = "Trung lập";
         jfa = "Nhóm";
         jga = "Tìm Nhóm";
         jha = "Điểm hiếu chiến của bạn hiện tại là ";
         jia = new String[]{"Bạn bè", "Thù Địch"};
         jja = "Bạn chưa kết bạn với ai";
         jka = "chờ xác nhận";
         jla = "đã thêm bạn vào danh sách bạn bè";
         jma = "Bạn đã thêm";
         jna = "vào danh sách";
         joa = "Bạn và";
         jpa = new String[]{"Cửa hàng", "Bản thân", "Bản đồ", "Tổng hợp", "Thoát", "Trang sức", "Tính năng", "Dược khóa", "Dược phẩm", "Tạp hóa khóa", "Tạp hóa", "Cường hóa", "Luyện hóa", "Luyện hóa khóa", "Thủ khố", "Tách trang bị", "Khu vực", "Giao dịch", "Tin nhắn", "Chọn Nhân vật"};
         jqa = new String[]{"Hỗ trợ bị động", "Chủ động sử dụng", "Chủ động sử dụng", "Chủ động sử dụng", "Chủ động sử dụng"};
         jra = new String[]{"Nhân vật: ", "Hiếu chiến: ", "Trình độ: ", "Lớp: ", "", "HP: ", "MP: ", "Tốc độ: ", "Tấn công: ", "Hỏa chống: ", "Băng chống: ", "Phong chống: ", "Giảm sát thương: ", "Độ chính xác: ", "Khả năng né đòn: ", "Chí mạng: ", "Phản đòn cận chiến: ", "Cường khắc: ", "Hạ khắc: ", "Điểm hoạt động: "};
         jsa = " lần";
         jta = new String[]{"Học Giả", "Hạ nhẫn", "Trung Nhẫn", "Thượng Nhẫn", "Nhẫn Giả"};
         jua = new String[]{"Điểm hoạt động: ", "Danh vọng vũ khí: ", "Danh vọng dây chuyền: ", "Danh vọng nhẫn: ", "Danh vọng ngọc bội: ", "Danh vọng bùa: ", "Danh vọng nón: ", "Danh vọng áo: ", "Danh vọng găng tay: ", "Danh vọng quần: ", "Danh vọng giày: ", "Hoàn thành NV mỗi ngày: ", "Truy bắt Tà Thú còn: ", "Học sách tiềm năng sơ: ", "Học sách kỹ năng sơ: ", "Gia tộc: ", "Vào hang động còn: ", "Điểm tinh tú: ", "Số lần ăn bánh phong lôi: ", "Số lần ăn bánh băng hỏa: "};
         jva = new String[]{"Tên: ", "Giới tính: ", "Tóc: "};
         jwa = new String[]{"Nữ", "Nam"};
         jxa = new String[]{"Sức mạnh", "Thân pháp", "Thể lực", "Chakra"};
         jya = "Chưa có ai cừu sát bạn";
         jza = "Bạn đã thắng #.";
         kaa = "Bạn đã thua #.";
         kba = "Cuộc so tài giữa bạn và # đã kết thúc";
         kca = new String[]{"", "Tinh Anh", "Thủ Lĩnh", "Tà Thú"};
         kda = " bắt đầu cừu sát bạn";
         kea = "Điểm tiềm năng";
         kfa = "Điểm kỹ năng";
         kga = "Không đủ MP để sử dụng";
         kha = "Chỉ được vật phẩm không khóa";
         kia = "Chỉ được chọn vật phẩm không khóa và không có hạn sử dụng";
         kja = "Chỉ được chọn Đá để luyện cấp";
         kka = "Chỉ được chọn Đá, Trang bị, và Bảo hiểm để nâng cấp";
         kla = "Chỉ được chọn Trang bị và vật phẩm Hoán chuyển.";
         kma = "Trang bị không thể nâng cấp";
         kna = "Trang bị đã nâng cấp tối đa";
         koa = "Chỉ được chọn trang bị đã nâng cấp mới có thể tách được";
         kpa = "Vật phẩm giao dịch đã đầy";
         kqa = "Số lượng đã đầy";
         kra = "Bạn không đủ điểm cộng";
         ksa = "Bạn chưa nhập điểm cộng";
         kta = "Bạn chưa nhập thông tin loại thẻ";
         kua = "Bạn chưa nhập thông tin mệnh giá.";
         kva = "Bạn chưa nhập thông tin số seri";
         kwa = "Bạn chưa nhập thông tin khoảng thời gian nạp.";
         kxa = "Bạn chưa nhập vào tên cần thêm";
         kya = "Nhập điểm";
         kza = "Nhập Xu";
         laa = "Nhập số lượng";
         lba = "Tên tài khoản";
         lca = "Xu";
         lda = "Yên";
         lea = "Lượng";
         lfa = "Cất vào hành trang";
         lga = "Bạn có thật sự muốn bãi nhiệm chức vụ của người này không?";
         lha = "Trục xuất thành viên sẽ bị giảm ngân sách gia tộc (xem chi tiết tại Npc Kanata). Bạn có thật sự muốn trục xuất người này không?";
         lia = "Tự rời khỏi gia tộc sẽ bị giảm xu trong hành trang (xem chi tiết tại Npc Kanata). Bạn có muốn rời khỏi không?";
         lja = "Sau khi sử dụng vật phẩm sẽ bị khóa. Bạn có muốn sử dụng không?";
         lka = "Sau khi bán vật phẩm sẽ không thể phục hồi. Bạn có muốn bán vật phẩm này không?";
         lla = new String[][]{{"nón"}, {"vũ", "khí"}, {"áo"}, {"vòng", "cổ"}, {"găng", "tay"}, {"nhẫn"}, {"quần"}, {"bội"}, {"giày"}, {"bùa"}, {"thú", "nuôi"}, {"mặt", "nạ"}, {"ninja", "yoroi"}, {"gia", "tộc"}, {"chưa", "mở"}, {"bí", "kíp"}, {"áo", "giáp"}, {"yên", ""}, {"cương", ""}, {"trang", "sức"}, {"động", "cơ"}, {"định", "vị"}, {"bộ", "đk"}, {"bình", "nitro"}};
         lma = new String[]{"Chưa vào trường", "Trường: Hirosaki", "Trường: Ookaza", "Trường: Haruna"};
         lna = new String[]{"", "Thuộc tính: Hỏa", "Thuộc tính: Thủy", "Thuộc tính: Phong", "", "", ""};
         loa = "Bạn nhận được";
         lpa = "Bạn chưa nhập vào số lương";
         lqa = "Không thể bán trang bị đã nâng cấp";
         lra = "Bạn không đủ xu để chuyển.";
         lsa = "Bạn không đủ xu để cất";
         lta = "Bạn không đủ xu để rút";
         lua = "Bạn không đủ số lượng để bán";
         lva = new String[]{"Thành công, trang bị được lên cấp ", "Thất bại, trang bị trở về cấp ", "Trang bị được nâng cấp tối đa", "Trang bị cấp"};
         lwa = new String[]{"Khảm ngọc thành công", "Khảm ngọc thất bại"};
         lxa = "tháng";
         lya = "tuần";
         lza = "ngày";
         maa = "giờ";
         mba = "giây";
         mca = "phút";
         mda = "Ảnh hưởng";
         mea = "Phạm vi";
         mfa = "MP mất";
         mga = "Khoảng cách thi triển";
         mha = "Phải có từ 2 viên đá trở lên mới có thể luyện được";
         mia = "Giới tính không phù hợp";
         mja = "Không có người chơi khác";
         mka = "Trình độ của bạn chưa đạt yêu cầu";
         mla = "Đá đã đạt cấp độ tối đa";
         mma = "Đá sau khi luyện cấp sẽ bị khóa. Bạn có muốn tiếp tục không?";
         mna = "Bạn không đủ xu để luyện đá";
         moa = "Bạn không đủ lượng để nâng cấp trang bị";
         mpa = "Bạn không đủ xu hoặc yên để nâng cấp trang bị";
         mqa = "Nhiều đá quá sẽ bị lãng phí. Bạn có chắc chắn muốn nâng cấp?";
         mra = "Sau khi nâng cấp trang bị sẽ bị khóa. Bạn có muốn tiếp tục không?";
         msa = "Không thể tách trang bị chưa nâng cấp";
         mta = "Hành trang không đủ chỗ trống";
         mua = "Bạn có thật sự muốn tách không?";
         mva = "Bạn có thật sự muốn chuyển hóa không?";
         mwa = "mời bạn giao dịch. Bạn có muốn giao dịch không?";
         mxa = "mời bạn vào tộc. Bạn có muốn là thành viên của gia tộc '#' không?";
         mya = "muốn xin vào gia tộc. Bạn có đồng ý không?";
         mza = "muốn tỷ thí với bạn. Bạn có đồng ý không?";
         nba = "mời bạn vào nhóm. Bạn có muốn vào không?";
         nca = "muốn xin vào nhóm. Bạn có đồng ý không?";
         nda = "Chuyển hóa trang bị thành công.";
         nea = new String[]{"Giới tính: nữ", "Giới tính: nam"};
         nfa = "Khu vực";
         nga = "Dân số";
         nha = "Nhóm";
         nia = "Hiện tại bạn không vào nhóm nào";
         nja = "lần";
         nka = new String[]{"Thông tin", "Thành viên", "Nhà Kho", "Thống Kê", "Thần Thú"};
         nla = new String[]{"Gia tộc: ", "Tộc trưởng: ", "Thành viên: ", "Cấp: ", "Kinh nghiệm: ", "Ngân sách: ", "Thành lập: ", "Cống hiến: ", "Phí duy trì: ", "Phí nâng cấp: ", "Vào Lãnh Địa Gia Tộc: còn ", "Cống hiến tuần: ", "Sử dụng lệnh bài còn: "};
         nma = new String[]{"xu lúc", "Thành lập gia tộc, ngân sách nhận", "bị trục xuất, ngân sách trừ", "đóng góp quỹ gia tộc, ngân sách tăng", "rút quỹ gia tộc, ngân sách giảm", "Thu phí duy trì gia tộc, ngân sách giảm", "nâng cấp gia tộc, ngân sách giảm"};
         nna = "Hiện tại bạn chưa gia nhập gia tộc";
         noa = "Phát cho Thành viên";
         npa = new String[][]{{"Trường Hirosaki"}, {"Trường Haruna"}, {"Trường Ookaza"}, {"Làng", "Làng Kojin", "Làng Sanzu", "Làng Tone", "Làng chài", "Làng Chakumi", "Làng Echigo", "Làng Oshin"}, {"Khu vực"}};
         nqa = new String[]{"Nón", "Nhân", "Áo", "Dây chuyền", "Găng tay", "Nhẫn", "Quần", "Ngọc bội", "Giày", "Bùa"};
         nra = new String[]{"Kích ẩn", "Kích cấp độ"};
         nsa = new String[]{"", "Hỏa", "Thủy", "Phong"};
         nta = new String[]{"Nhân vật", "Level", ""};
         nua = "Vô chiêu thắng hữu chiêu. Hiện tại bạn chưa có chiêu để đánh.";
         nva = "Bạn chưa có vũ khí. Xin vào Menu/Bản Thân/Trang bị để kiểm tra";
         nwa = "Vật phẩm đã bị khóa";
         nxa = "Vật phẩm, trang bị và đá";
         nya = "Mức giá (xu)";
         nza = "Mức giá (yên)";
         oaa = "Đã hết hiệu quả thức ăn";
         oba = "Level của bạn không đủ để sử dụng";
         oca = "Đã hết bình MP";
         oda = "Đã hết bình HP";
         oea = new String[]{"Giao dịch", "Tỷ thí", "Cừu sát", "Kết bạn", "Mời vào nhóm", "Phục hồi", "Xem thông tin", "Chat riêng", "Mời vào tộc", "Xin vào tộc", "Chặn xin vào tộc", "Tự Hồi Sinh", "Cấm Chat"};
         ofa = "Bạn đang ở khu vực này";
         oga = new String[]{"Hãy đi tìm ", " ở ", " để nhận nhiệm vụ.", "Bạn đã hoàn thành hết nhiệm vụ phiên bản này, vui lòng chờ cho đến khi ra phiên bản tiếp theo."};
         oha = new String[]{"Kiệt sức", "Đứng nhìn", "Quay về", "Hồi sinh tại chỗ (1 lượng)"};
         oia = "Sau khi gia nhập vào lớp học, thì có thể nhận nhiệm vụ từ hiệu trưởng";
         oja = "Tạo nhóm";
         oka = "Rời nhóm";
         ola = "Nhóm trưởng";
         oma = "Khóa nhóm";
         ona = "Mở nhóm";
         ooa = "Xin gia nhập";
         opa = "Tìm lại";
         oqa = "Hiện tại bạn chưa có nhóm";
         ora = "Chưa có thông tin";
         osa = "Hiện tại không tìm thấy nhóm";
         ota = new String[]{"PK Thường", "PK Phe", "PK Bang", "PK Đồ Sát"};
         oua = new String[]{"Trạng thái PK", "Bạn bè", "Thù Địch", "Nhóm", "Tìm nhóm", "Gia tộc", "Bảo vệ tài khoản", "Tự động", "Bán Shinwa", "Luyện thạch", "Tinh luyện", "Dịch chuyển"};
         ova = new String[]{"Bản đồ", "Nhiệm vụ", "Gia tộc"};
         owa = new String[]{"Tộc trưởng", "Tộc phó", "Trưởng lão", "Ưu tú", "Thành viên"};
         oxa = new String[]{"(TT)", "(TP)", "(TL)", "(UT)"};
         oya = new String[]{"Chỉ hiện Online", "Rời khỏi", "Thông báo", "Đóng góp", "Rút quỹ", "Nâng Cấp", "Mời vào lãnh địa", "Mời vào Gia tộc chiến", "Khai mở"};
         oza = "SX theo C.Hiến tuần";
         paa = new String[]{"Trục xuất", "Nhường", "Kết bạn"};
         pba = " được lên làm nhóm trưởng.";
         pca = "Bạn bị đuổi ra khỏi nhóm";
         pda = "Mời vào nhóm";
         pea = "Thêm";
         pfa = "Vũ khí không thích hợp.";
         pga = "Bạn có muốn xóa người này ra khỏi danh sách?";
         pha = new String[]{"Bạn phải vào trường để tăng điểm"};
         pia = new String[]{"Sức mạnh = Tấn công", "Thân pháp = né,chính xác", "Thể lực = HP", "Chakra = MP"};
         pja = new String[]{"Không cần tăng sức mạnh", "Thân pháp = né,chính xác", "Thể lực = HP", "Chakra = Tấn công, MP"};
         pka = "Đóng tab hiện tại";
         pla = new String[]{"Công cộng", "Bạn có thể chat với người đứng gần tại đây"};
         pma = new String[]{"Chung nhóm", "Bạn có thể chat với người trong cùng nhóm tại đây"};
         pna = new String[]{"Kênh thế giới", "Bạn mất 5 lượng mỗi lần chat kênh thế giới.", "Tất cả người đang online đều thấy bạn chat.", "Bạn sẽ bị khóa tài khoản nếu chửi bậy, quảng cáo wap web trên kênh thế giới."};
         poa = new String[]{"Gia tộc", "Bạn có thể chat với người trong gia tộc tại đây"};
         ppa = "Chặn kênh thế giới: ";
         pqa = "Chặn chat riêng: ";
         pra = "Bổ nhiệm";
         psa = "Bãi nhiệm";
         pta = "Trục xuất";
         pua = "Mật khẩu phải có độ dài là 6 ký tự.";
         pva = "Mật khẩu bảo vệ chỉ cho nhập số.";
         pwa = "Mật khẩu bảo vệ không được chứa số 0 ở đầu.";
         pxa = "Mật khẩu bảo vệ chưa đúng.";
         pya = "Để sử dụng chức năng này bạn phải có Vạn biến lệnh.";
         pza = "Kích hoạt chức năng này phải tốn 10.000 yên. Bạn có muốn kích hoạt không ?";
         qaa = "Nhập mật khẩu bảo vệ";
         qba = "Nhập số điện thoại đăng ký";
         qca = "Bạn chưa nhập số điện thoại đăng ký.";
         qda = "Để lấy mật khẩu cho '#'. Bạn phải sử dụng số điện thoại đăng ký cho tài khoản này.";
         qea = "Đổi mật khẩu";
         qfa = "Huỷ bảo vệ";
         qga = "Mật khẩu cũ";
         qha = "Mật khẩu mới";
         qia = "Bạn học được ";
         qja = "Nhập thông báo";
         qka = "Nhập số xu cần rút";
         qla = "Nhập số xu đóng góp cho gia tộc";
         qma = "Nhập thông tin loại thẻ và mệnh giá";
         qna = "Nhập thông tin số seri và khoảng thời gian nạp";
         qoa = "Nhập số lượng tách";
         qpa = "Mệnh giá";
         qqa = "Loại thẻ";
         qra = "Số seri";
         qsa = "Thời gian nạp";
         qta = "Chặn tin nhắn";
         qua = "Báo lỗi với Admin";
         qva = new String[]{"Gán phím tắt", "Gán vào 5 ô đánh"};
         qwa = "Gửi tin nhắn thành công";
         qxa = "Chúc mừng bạn đã gởi tin nhắn dự đoán thành công.";
         qya = "Không thể gửi tin nhắn";
         qza = "Tin nhắn gửi không thành công.";
         raa = "Không đủ xu để đóng góp";
         rba = "Số lượng tách không hợp lệ.";
         rca = "Giá trị nhập không hợp lệ.";
         rda = "Bạn có muốn hủy chức năng bảo vệ tài khoản không ?";
         naa = "muốn thách đấu với bạn ở lôi đài. Bạn có đồng ý không?";
         rea = "Sắp xếp theo giá";
         rfa = "Sắp xếp theo cấp";
         rga = "Sắp xếp theo tên";
         rha = "Vật phẩm đã được gởi bán vào gian hàng";
         ria = "Mức phí cho mỗi lần bán là 5.000 xu";
         rka = "Bạn có muốn bán vật phẩm với giá # xu không ?";
         rla = "Bạn có muốn mua vật phẩm với giá # xu không ?";
         rma = "Người bán";
         rna = "còn";
         roa = "gần";
         rpa = "hết giờ";
         rqa = new String[]{"Đá", "Nón", "Vũ khí", "Áo", "Dây chuyền", "Găng tay", "Nhẫn", "Quần", "Ngọc bội", "Giày", "Bùa", "Linh tinh"};
         rja = " Vật phẩm bán được chịu thuế là 1%";
         ida = "Kinh nghiệm";
         rra = "Thông báo Server";
         rsa = "Giới thiệu bạn bè";
         rta = "Lật hình";
         rua = "Số lượt lật còn lại của bạn là: ";
         rva = "muốn thách đấu với bạn và cả gia tộc. Bạn có đồng ý không?";
         rwa = "Max options";
         rxa = "Mời người này";
         rya = "Mời tất cả";
         rza = "'#' mời bạn vào gia tộc chiến. Bạn có muốn vào không?";
         saa = "Nhập tên thành viên";
         sba = new String[][]{{"Yêu cầu: gia tộc đạt cấp 5.", "Phí khai mở: 1.000.000 xu gia tộc."}, {"Yêu cầu: gia tộc đạt cấp 10.", "Phí khai mở: 5.000.000 xu gia tộc."}, {"Yêu cầu: gia tộc đạt cấp 15.", "Phí khai mở: 10.000.000 xu gia tộc."}, {"Yêu cầu: gia tộc đạt cấp 20.", "Phí khai mở: 20.000.000 xu gia tộc."}, {"Yêu cầu: gia tộc đạt cấp 25.", "Phí khai mở: 30.000.000 xu gia tộc."}};
         sca = new String[]{"Dùng HP khi còn dưới: ", "Dùng MP khi còn dưới:", "Dùng thức ăn cấp: ", "Dùng chiêu hổ trợ", "Dùng khiên mana", "Dùng đốt quái & ẩn thân", "Dùng phân thân", "Nhặt yên", "Nhặt HP, MP", "Nhặt N.Liệu(Đá)", "Luyện đá Max", "Nhặt Trang Bị", "Nhặt Trang Bị Lạ", "Nhặt VP Nhiệm Vụ", "Nhặt VP Sự Kiện", "Nhặt All", "Nhặt SVC", "Không nhặt gì cả", "Auto TTT", "AutoTTC", "ReMap", "Tàn sát map trống", "Auto Mua Thức Ăn", "TS khi hết MP", "Auto Reconnect", "Chuyển Map Hết Boss", "Săn TATL", "Đánh Quái Thường", "Đánh Tinh Anh", "Đánh Thủ Lĩnh", "Cộng tiềm năng", "Cộng kĩ năng", "Đánh theo nhóm", "Né PK", "Auto Làng Cổ", "Auto Mua Cổ Lệnh"};
         sda = "Dùng phím < và > để đổi giá trị";
         sea = "Chạm vào ô thông số để đổi giá trị";
         sfa = "Khoảng cách quá xa, không thể phục hồi cho người khác được";
         sga = "     Nhập giá trị phần trăm thấp tối thiểu            (Từ 10 đến 90)";
         sha = new String[]{"Cấp 1", "Cấp 10", "Cấp 20", "Cấp 30", "Cấp 40", "Cấp 50", "Cấp 60", "Cấp 70"};
         sia = new String[]{"Cấp 1", "Cấp 2", "Cấp 3", "Cấp 4", "Cấp 5", "Cấp 6", "Cấp 7", "Cấp 8", "Cấp 9", "Cấp 10", "Cấp 11", "Cấp 12"};
         sja = "Tài khoản đang được bảo vệ, vui lòng mở khóa.";
         ska = "Sinh lực";
         sla = "Tên thú cưỡi";
         sma = new String[]{"Luyện thạch cấp cao hơn bằng cách", "dùng 9 thạch cùng loại hoặc 3 thạch sơ", "và đá 11 hoặc 3 thạch trung và đá 12."};
         sna = "Chỉ được chọn Tử tinh thạch sơ và trung cấp";
         soa = "Chỉ được chọn Đá và Tử tinh thạch để luyện";
         spa = "Chỉ cần dùng 1 viên đá để luyện";
         sqa = "Cần kết hợp 3 Tử tinh thạch (trung) và đá 12 hoặc 3 tử tinh thạch (sơ) đá 11";
         sra = "Chỉ được chọn đá cấp 11 trở lên";
         ssa = "Chỉ được chọn Tử thiên thạch cùng loại";
         sta = "Phải có từ 3 Tử tinh thạch trở lên mới có thể luyện được";
         sua = "Số lượng Tử tinh thạch quá nhiều";
         sva = "Vật phẩm này không thể tinh luyện";
         swa = "Cần phải có đủ 20 chuyển tinh thạch để dịch chuyển trang bi";
         sxa = "Vật phẩm này không dùng trong dịch chuyển";
         sya = "Cất kẹo";
         sza = "Độ tinh luyện";
         taa = "Động cơ";
         tba = "Nhiên liệu";
         tca = "Cho kẹo";
         tda = new String[]{"tử tinh", "tử tinh thạch sơ", "tử tinh thạch trung", "tử tinh thạch cao"};
         tea = "Vật phẩm đã tinh luyện đến mức tối đa";
      } else {
         if (aea == 1) {
            aga = "This gem can't roasting.";
            afa = "This gem reached max level.";
            aha = "Register account to keep your character safe. Do you want to register?";
            aia = "Hidden quest";
            aja = "- Get 1 aggressive point.";
            aka = "- Complete the cave of near school yard 1 times.";
            ala = "- Complete hunting wild beast 1 times.";
            ama = "- Upgrade equipment successful 1 times.";
            ana = "- Complete daily quest 10 times.";
            aoa = "- Get 1000 battlefield points.";
            apa = "- Complete seven beasts gate 1 times.";
            aqa = "- Enjoy lucky card 3 times.";
            var10000 = new String[]{"Katana", "Bokken", "Shuriken", "Tessen", "Kunai", "General Server"};
            ata = "Win rate";
            aua = "Your coin: ";
            ava = "Players: ";
            awa = "Lucky draw";
            axa = "Join now";
            tka = "Continue";
            tfa = "Your account has not been verified. If you delete the game, or log another account, your character will lose playing forever.";
            tga = "New Play";
            tha = "Play";
            tia = "Change Username";
            tja = "Server: ";
            aya = "rank";
            aza = "Challenge";
            baa = "Info";
            bca = new String[]{"Press change focus button to show all players on map", "For keyboard phones, assign shortcut keys 7,8,9 (or Q,W,E) to use skills.", "Berserk mode adds +2 agressive points.  Kill adds +1 agressive", "Sword, Kunai,and Blade increases Strength, Constitution, Dexterity", "Bow, Shuriken and Fan increases Chakra, Constitution, Dexterity", "Training as a team will earn experience and complete tasks faster", "Fighing other players on the battlefield will decrease combative points.", "When separated from the stone equipped, you will collect half amount of stone at the beginning.", "If you have enough action points, you can exchange coins from kin.", "The highest daily achievement in the arena will earn a reward.", "Find Rikudou to get into the arena.", "Precautionary measures cost money but will Increase the success rate of upgrading items", "When you reach Level 20, find Okanechan to received 10 gold bars.", "Gold bars will be split to 3 characters in 1 account"};
            bba = "Term";
            bda = "NSO TGAME";
            bea = "Wait";
            bfa = "Menu";
            bga = "Need";
            bha = "Move to";
            bia = "Language";
            bja = "Clear cache";
            bka = new String[]{"Tiếng việt", "English"};
            var10000 = new String[]{"ភាសាខ្មែរ", "ភាសាអង់គ្លេស"};
            bla = "Exit game to change the language ?";
            bma = "Close";
            bna = "Hide";
            boa = "Auto";
            bpa = "Stand";
            bqa = "by";
            bra = "Lock";
            bsa = "Unlock";
            bta = "Seri number";
            bua = "Card code";
            bva = "On";
            bwa = "Off";
            bxa = "Open link";
            bya = "Charge";
            bza = "Active";
            caa = "Config";
            cba = "Delete";
            cca = "View";
            cda = "Continue";
            cea = "Inventory code";
            cfa = "Scratch card";
            cga = "Next";
            cha = "Use";
            cia = "Sort";
            cja = "Throw it away";
            cka = "Split";
            cla = "Equipment has been split, you get ";
            cma = "Yes";
            cna = "Get out";
            coa = "Get out";
            cpa = "Withdraw coins";
            cqa = "Store coins";
            cra = "Transfer coins";
            csa = "Store";
            cta = "Sell";
            cua = "Sell more";
            cva = "Sell all";
            cwa = "Price";
            cxa = "Buy";
            cya = "Buy more";
            cza = "No";
            daa = "Exit";
            dba = "Chat";
            dca = "OK";
            dda = "Account";
            dea = "Password";
            dfa = "Re-input";
            dga = "Account";
            dha = "Pass";
            dia = "re";
            dja = "Please restart game";
            dka = "Re-input password";
            dla = "Remember";
            dma = "Uncheck";
            dna = "Register";
            doa = "High Graphic";
            dpa = "Low Graphic";
            dqa = "Please input account name";
            dra = "Account does not allow special characters.";
            dsa = "You haven't added a password.";
            dta = "Your passwords do not match.";
            dua = "Account name must have at least five characters";
            dva = "Wrong password.";
            dwa = new String[]{"To register with name", "you have to follow the game rule."};
            dxa = "What operator are you using? (You can recheck it in Menu)";
            dya = "Are you using your phone number to create account ?";
            dza = "private message";
            eaa = new String[]{"message clan, group", "clan messages", "group message"};
            eba = "escort";
            eca = "Plus";
            eda = "Plus more";
            eea = "potential point";
            efa = "skill point";
            ega = "Accept";
            eha = "Cancel";
            eia = "List";
            eja = "Time";
            eka = "Achievement";
            ela = "Max";
            ema = "Accumulate";
            ena = "Connecting";
            eoa = "Registering";
            epa = "Logging";
            eqa = "Not finished";
            era = "Time to finish";
            esa = "Teamwork";
            eta = "Select";
            eua = "Uncheck";
            eva = "Select items to view the information.";
            ewa = "Assign";
            exa = "Result";
            eya = "Review";
            eza = "Level";
            faa = "Level";
            fba = "Do you want to exit?";
            fca = "Please rename your character";
            fda = "This server is maintained or overloaded. Please try again later or choose another server.";
            fea = "Create";
            ffa = "Name";
            fga = "Name of character you want to friend";
            fha = "Friend link successful.";
            fia = "Loading... ";
            fja = "Close";
            fka = "Get reward";
            fla = "lucky gift";
            fma = "Inventory was expanded";
            fna = "Distance too far for escort, quest failed";
            foa = "The escort was wounded, quest failed";
            fpa = "forever";
            fqa = "Not upgrade";
            fra = "Can not upgrade.";
            fsa = "Use special items to upgrade";
            fta = "Train";
            fua = "Stone train successful, you get";
            fva = new String[]{"Just transfer same type equipment", " or higher.", "Will lock fitted after transformation.."};
            fwa = "failure, you get";
            fxa = "Message sent, please wait for confirmation.";
            fya = "Can not send message. Please check you balance or restart the game.";
            fza = "Sending Coins";
            gaa = "Start";
            gba = "Choose at least 2 stones or more";
            gca = "Choose the equipment that you want to split the Stone";
            gda = "Choose item and coins to exchange";
            gea = "Move to luggage to choose";
            gfa = "Change";
            gga = "Cell";
            gha = "Cells";
            gia = new String[]{"Key Q", "Key W", "Key E"};
            gja = new String[]{"Key 7", "Key 8", "Key 9"};
            gka = new String[][]{{"tomboy", "with brooch", "pony tail", "curly"}, {"head band", "afro", "samurai", "spike"}};
            gla = new String[]{"Inventory", "Skill", "Potential", "Info", "Equipment", "Mounts"};
            gma = new String[]{"Costume shop", "Inventory"};
            gna = new String[]{"Cap", "Inventory"};
            goa = new String[]{"Cloth", "Inventory"};
            gpa = new String[]{"Gloves", "Inventory"};
            gqa = new String[]{"Pants", "Inventory"};
            gra = new String[]{"Shoes", "Inventory"};
            gsa = new String[]{"Necklace", "Inventory"};
            gta = new String[]{"Ring", "Inventory"};
            gua = new String[]{"Gems", "Inventory"};
            gva = new String[]{"Charms", "Inventory"};
            gwa = new String[]{"Weapons", "Inventory"};
            gxa = new String[]{"Medicine", "Inventory"};
            gya = new String[]{"Medicine", "Inventory"};
            gza = new String[]{"Food", "Inventory"};
            haa = new String[]{"Food", "Inventory"};
            hba = new String[]{"Upgrade", "Inventory"};
            hca = new String[]{"Stand", "Inventory"};
            hda = new String[]{"Transfer", "Inventory"};
            hea = new String[]{"Training Stone", "Inventory"};
            hfa = new String[]{"Inventory", "Inventory"};
            hga = new String[]{"Shop", "Book Store", "Fashion Store", "Clan Store"};
            hia = new String[]{"Split Stone", "Inventory"};
            hja = new String[]{"Trade", "Inventory"};
            hka = new String[]{"Upgrade essence", "Inventory"};
            hla = new String[]{"Add attributes", "Inventory"};
            hma = new String[]{"Enhance equipment", "Inventory"};
            hna = new String[]{"Socketing", "Inventory"};
            hoa = new String[]{"Leveling gem", "Inventory"};
            hqa = new String[]{"Gem Roasting", "Inventory"};
            hra = new String[]{"Extract gem", "Inventory"};
            hpa = new String[]{"Completed quest", "Inventory"};
            tla = new String[]{"Pickup", "Inventory"};
            var10000 = new String[]{"Del", "Inventory"};
            tma = "Delete";
            tna = "Add";
            ara = "I will help decrease bad options of this gem.";
            asa = "I will help you extract gem from this item.";
            hsa = new String[]{"- Use kin incase not enough coin", "- Move to inventory to choose stone", "- Amount of stones from 2 to 24"};
            hta = new String[]{"- Use coin incase not enough kin", "- Upgrading need Gold bar", "- Choose Equiptment and stone only", "Your equipment has reached max level"};
            hua = new String[]{"- Use coin incase not enough kin", "- Choose Equiptment and Gem"};
            hva = "Lock Transfer";
            hwa = "- Train Stone to level";
            hxa = "- Need: # kin";
            hya = "- Need: # Gold bars";
            hza = "- Need: # coins";
            iaa = "- Percentage of success.";
            iba = "(success ";
            ica = "Add";
            iea = "Locked";
            ifa = "Killed";
            iga = "Arrest Beast";
            iha = "Kill Elitez";
            iia = "Kill Chief";
            ija = "Protect the child";
            ika = "No lock";
            ila = "Expires";
            ima = "Price: # kin";
            ina = "Price: # coins";
            ioa = "Price: # clan coins";
            ipa = "Price: # kin";
            iqa = "Price: # gold bars";
            ira = "Gold bar";
            isa = "Do not have";
            ita = "Next level: level #";
            iua = "Current level: level #";
            iva = "Maximum level";
            iwa = "Reached maximum level";
            ixa = "Require: level";
            iya = "Class: ";
            iza = new String[]{"Main quest", "Sub quest"};
            jaa = "Quest";
            jba = "Obtain quest at";
            jca = "White Side";
            jda = "Black Side";
            jea = "Neutral";
            jfa = "team";
            jga = "Find team";
            jha = "Your current aggressive points are ";
            jia = new String[]{"Friends", "Hostile"};
            jja = "You are not friends with anyone";
            jka = "waiting confirmation";
            jla = "added you to friends list";
            jma = "You have added";
            jna = "to the list";
            joa = "You and";
            jpa = new String[]{"store", "Myself", "Map", "General", "Exit", "Jewellery", "Feature", "Pharmaceutical Key", "Pharmacy", "Grocery Key", "Grocery", "Strengthen", "Training", "Training key", "Inventory", "Split Equipment", "Area", "Trade", "Message"};
            jqa = new String[]{"Passive Support", "Active use", "Active use", "Active use", "Active use"};
            jra = new String[]{"Character: ", "Agressive: ", "Level: ", "Class: ", "", "HP:", "MP: ", "Speed: ", "Attack: ", "Anti Fire: ", "Anti Ice: ", "Anti Wind: ", "Reduce Pain: ", "Accurate point:", "Dodge ability: ", "Critical: ", "Close combat strike back: ", "Anti chakra: ", "Anti chakra back: ", "Action points: "};
            jsa = " times";
            jta = new String[]{"Genin", "Chunin", "Jounin", "Kage"};
            jua = new String[]{"Action point: ", "Weapon Fame: ", "Necklace Fame: ", "Ring Fame: ", "Gems Fame: ", "Charm Fame: ", "Hat Fame: ", "Cloth Fame: ", "Gloves Fame: ", "Pants Fame: ", "Shoes Fame: ", "Accomplish daily quest: ", "Arrest Beast: ", "Read the basic potential book: ", "Read the basic skill book: ", "Clan: ", "Cave time left: ", "Star Fame: ", "Wind Thunder Mooncake: ", "Ice Fire Mooncake: "};
            jva = new String[]{"Name: ", "Gender: ", "Hair: "};
            jwa = new String[]{"Female", "Male"};
            jxa = new String[]{"Strength", "Dexterity", "Constitution", "Chakra"};
            jya = "You were not killed by anyone.";
            jza = "You won #.";
            kaa = "You lost #.";
            kba = "Your fight match between you and # is over.";
            kca = new String[]{"", "Elitez", "Chief", "Beast"};
            kda = " try to kill you";
            kea = "Potential point";
            kfa = "Skill point";
            kga = "Not enough MP to use";
            kha = "Only select unlocked items";
            kia = "Only select unlocked items that haven't expired";
            kja = "Just choose Stones to train";
            kka = "Just choose Stone, Equipment and upgrade insurance.";
            kla = "Just choose Equipment and conversion items.";
            kma = "Can not upgrade";
            kna = "Maximum upgrade";
            koa = "Only upgraded item or equipment to split.";
            kpa = "Items for Trading are full.";
            kqa = "Amount is Full.";
            kra = "Not enough points.";
            ksa = "Please input added points.";
            kta = "You need to input card information.";
            kua = "You need to input card value information.";
            kva = "You need to enter serial number.";
            kwa = "You need to enter topup times.";
            kxa = "You need to enter a name";
            kya = "Enter Points";
            kza = "Enter Coins";
            laa = "Enter quantity";
            lba = "Username";
            lca = "Coin";
            lda = "Kin";
            lea = "Gold bar";
            lfa = "Put in inventory";
            lga = "Do you really want to dismissed this one?";
            lha = "Expulsion of members will reduce Clan budgets (see details in Kanata NPC). Do you want to dismiss them?";
            lia = "Leaving clan will reduce your coins (see Kanata for details.)  Are you sure you want to leave?";
            lja = "After using this item, it will be locked. Do you want to use it?";
            lka = "Sold items can not be recovered. Do you want to sell this item?";
            lla = new String[][]{{"cap"}, {"wea", "pon"}, {"cloth"}, {"neck", "lace"}, {"glo", "ves"}, {"ring"}, {"pants"}, {"gems"}, {"shoes"}, {"charm"}, {"pet"}, {"mask"}, {"ninja", "yoroi"}, {"clan", "item"}, {"Emp", "ty"}, {"Ancient", "Book"}, {"Ar", "mor"}, {"Sad", "dle"}, {"Tas", "sels"}, {"Coro", "net"}, {"Eng", "ine"}, {"Sat", "nav"}, {"ECU", ""}, {"N20", ""}};
            lma = new String[]{"Not a student", "School: Hirosaki", "School: Ookaza", "School: Haruna"};
            lna = new String[]{"", "Attribute: Fire", "Attribute: Water", "Attribute: Wind", "", "", ""};
            loa = "You got";
            lpa = "You have not entered the amount of gold bars.";
            lqa = "Can not sell upgraded equipment.";
            lra = "You don't have enough coins to move.";
            lsa = "You don't have enough coins to store.";
            lta = "You don't have enough coins to withdraw.";
            lua = "You don't have enough gold bars to sell.";
            lva = new String[]{"Success,  equipped with level up ", "failed, return level of equipment", "equipment upgraded maximum", "equipment level"};
            lwa = new String[]{"Success socketing", "Socketing has failed"};
            lxa = "month";
            lya = "week";
            lza = "day";
            maa = "hour";
            mba = "second";
            mca = ",minute";
            mda = "Number of target";
            mea = "Range";
            mfa = "MP cost";
            mga = "Cool down time";
            mha = "You need at least two stones to train.";
            mia = "Gender does not match";
            mja = "Don't have any one else";
            mka = "Your level is too low";
            mla = "Stone has reached the maximum level";
            mma = "Your stones after leveling will be blocked. Would you like to continue?";
            mna = "You don't have enough coins to level stone";
            moa = "You don't have enough gold bars to upgrade equipment";
            mpa = "You don't have enough coins to upgrade equipment";
            mqa = "Many training stones will be wasted. Are you sure you want to upgrade";
            mra = "After upgrade this item will be locked. Do you want to continue?";
            msa = "Can not split the unupgraded item.";
            mta = "Your luggage doesn't have enough space.";
            mua = "Do you really want to split this item?";
            mva = "Do you really want to convert?";
            mwa = "Welcome to trading. Do you want to trade?";
            mxa = "Welcome to the clan. Do you want to join Clan '#' ?";
            mya = "Do you want to join this clan?";
            mza = "wants to fight with you. Do you accept?";
            nba = "invite you to Party. Do you want to join?";
            nca = "ask you to join their Party. Do you accept?";
            nda = "Convert successful.";
            nea = new String[]{"Gender: Female", "Gender: Male"};
            nfa = "Area";
            nga = "Population";
            nha = "Party";
            nia = "At this moment, you have not joined any Party.";
            nja = "times";
            nka = new String[]{"Info", "Member", "Warehouse", "Statistic", "Guardian"};
            nla = new String[]{"Clan: ", "Clanmaster: ", "Member: ", "Level: ", "Experience: ", "Budget: ", "Establish: ", "Donation: ", "Maintenance fee: ", "Upgrade fee: ", "Enter the Territory of Clan: remain ", "Week donation: ", "Use Clan card mark: remain "};
            nma = new String[]{"Coins at", "Establish clan, budget has", "expulsion, budget decrease", "clan contribution, budget increase", "withdraw clan budget, budget decrease", "Fee for maintain clan, budget decrease", "upgrade clan, budget decrease"};
            nna = "You are not a member of any clan";
            noa = "Send to Clan Member";
            npa = new String[][]{{"Hirosaki School"}, {"Haruna School"}, {"Ookaza School"}, {"Village", "Kojin village", "Sanzu village", "Tone village", "Fish Village", "Chakumi Village", "Echigo Village", "Oshin Village"}, {"Area"}};
            nqa = new String[]{"Cap", "Ring", "Cloth", "Necklace", "Gloves", "Ring", "Pants", "Gems", "Shoes", "Charm"};
            nra = new String[]{"Active hidden", "Active level"};
            nsa = new String[]{"", "Fire", "Water", "Wind"};
            nta = new String[]{"Character", "Level", "Jewellery"};
            nua = "You do not have any special skills.";
            nva = "You do not have any special weapons. Go to Menu/Status/Equipment to check";
            nwa = "This item was locked.";
            nxa = "Items, accessories and stones";
            nya = "price (coin)";
            nza = "price (kin)";
            oaa = "You are hungry, eat some more";
            oba = "You level is too low to use this item";
            oca = "Out off MP";
            oda = "Out off HP";
            oea = new String[]{"Trade", "Fight", "Berserker", "Add friend", "Invite to Party", "Recover", "Check info", "Private chat", "Invite to clan", "Request to join clan", "Block request to joint clan", "Auto recover", "Cấm Chat"};
            ofa = "You are in ";
            oga = new String[]{"Let's find", " at ", " to get the quest.", "You have finished all quests this version, please wait for the next version."};
            oha = new String[]{"Exhausted", "Starring", "Come back", "Revive now (1 Gold bar)"};
            oia = "After joining a class, you can receive any quest from the principal.";
            oja = "Create team";
            oka = "Leave team";
            ola = "Teamleader";
            oma = "Lock team";
            ona = "Unlock team";
            ooa = "Ask to join party.";
            opa = "Refresh";
            oqa = "You are not a member of any team.";
            ora = "Empty information.";
            osa = "Cannot find any Party now.";
            ota = new String[]{"PK normal", "PK team", "PK clan", "PK Berserker"};
            oua = new String[]{"PK status", "Friend", "Enemy", "Party", "Find party", "Clan", "Protect account", "Auto", "Sell Shinwa", "Upgrade essence", "Enhance equipment", "Add attributes"};
            ova = new String[]{"Map", "Quest", "Clan"};
            owa = new String[]{"Clan Master", "Chief Elder", "Elder", "Elite", "Member"};
            oxa = new String[]{"(CM)", "(CE)", "(ED)", "(EL)"};
            oya = new String[]{"Online only", "Left", "Notice ", " Contribute ", " Withdraw funds ", " Upgrade ", " Invite to territory ", "Unlock"};
            oza = "Sort by dedicating week";
            paa = new String[]{"Expulsion", "Transfer", "Make friend"};
            pba = " You are promoted to team leader.";
            pca = "You were kicked off of team.";
            pda = "Invite to team";
            pea = "Add";
            pfa = "Inappropriated Weapons.";
            pga = "Do you want to delete this person from your friend list?";
            pha = new String[]{"Go to school to upgrade your marks."};
            pia = new String[]{"Strength = Attack", "Dexterity = dodge, accurate", "Strength = HP", "Chakra = MP"};
            pja = new String[]{"No need to upgrade strength", "Dexterity = dodge, accurate", "Strength = HP", "Chakra = Attack, MP"};
            pka = "Close current tab.";
            pla = new String[]{"Public chat", "You can chat with people around you here."};
            pma = new String[]{"Same party", "You can chat with your Party member here."};
            pna = new String[]{"Global chat", "You will lose 5 Gold Bars for each use.", "This message will broadcast to everybody.", "Your account will automatically be locked if you attempt to advestise any wap website, or use profanity."};
            poa = new String[]{"Clan", "Yon can chat with Clanmates in this place"};
            ppa = "Block global chat: ";
            pqa = "Block private chat: ";
            pra = "Appoint";
            psa = "Dismiss";
            pta = "Expulsion";
            pua = "Maximum 6 digits.";
            pva = "Just allow number digit for protected password.";
            pwa = "Protected password can not start with number 0.";
            pxa = "Wrong password.";
            pya = "To use this function, you have to have Multi Teleport Card.";
            pza = "To activate this function, you have to pay 10.000 kin. Do you want to activate?";
            qaa = "Password";
            qba = "input the mobile number that you want to register";
            qca = "You did not input the number that you used to register this game before.";
            qda = "To get the password for account '#'. You must use the phone number used to register this account.";
            qea = "Change pass";
            qfa = "Cancel protection";
            qga = "Old password";
            qha = "New password";
            qia = "You have learned ";
            qja = "Input your message content";
            qka = "Input the amount of coin to withdraw";
            qla = "Input the coin amount to donate to the Clan.";
            qma = "Input type of card and value";
            qna = "Input serie number and time of charging.";
            qoa = "Input amount of split time.";
            qpa = "Value";
            qqa = "Type of card";
            qra = "Seri number";
            qsa = "Time of charging";
            qta = "Block message";
            qua = "Submit this bug to Admin.";
            qva = new String[]{"Assign key", "Assign to 5 key"};
            qwa = "Send message success.";
            qxa = "Congratulations! your choice is correct.";
            qya = "Can not send message.";
            qza = "Send failure.";
            raa = "Not enough coin to contribute";
            rba = "The amount to split is invalid.";
            rca = "invalid input value.";
            rda = "Do you want to cancel Protect account function?";
            naa = "wants to challenge you in the battle arena. Do you agree?";
            rea = "Sort by price";
            rfa = "Sort by level";
            rga = "Sort by name";
            rha = "Item is sent for trading";
            ria = "Trading fee is 5.000 coin";
            rka = "Do you want to sell item with # coins ?";
            rla = "Do you want to buy item with # coins ?";
            rma = "Seller";
            rna = "remain";
            roa = "a few";
            rpa = "seconds";
            rqa = new String[]{"Stone", "Cap", "Weapon", "Cloth", "Necklace", "Gloves", "Rings", "Cloths", "Gems", "Shoes", "Charms", "Miscellaneous"};
            rja = "pay 1% of value as tax";
            ida = "Experience";
            rra = "Announcement";
            rsa = "Invite friends";
            rta = "Choose card";
            rua = "Flip remaining: ";
            rva = "Challenges you and your clan. Do you agree ?";
            rwa = "Max options";
            rxa = "Invite this person";
            rya = "Invite all";
            rza = "'#' invites you to join the clan war. Do you want to join?";
            saa = "Input member's name";
            sba = new String[][]{{"Requirement: Clan level 5", "Cost to Open: 1.000.000 clan coins."}, {"Requirement: Clan level 10.", "Cost to Open: 5.000.000 clan coins."}, {"Requirement: Clan level 15.", "Cost to Open: 10.000.000 clan coins."}, {"Requirement: Clan level 20.", "Cost to Open: 20.000.000 clan coins."}, {"Requirement: Clan level 25.", "Cost to Open: 30.000.000 clan coins."}};
            sca = new String[]{"HP: ", "MP: ", "Using food level: ", "Always using skill to support", "Dùng khiên mana", "Dùng đốt quái", "Dùng phân thân", "Pick up Kins", "Pick up Hp, MP", "Pick up Material", "Luyện đá Max", "Nhặt Trang Bị", "Nhặt Trang Bị Lạ", "Nhặt VP Nhiệm Vụ", "Nhặt VP Sự Kiện", "Nhặt All", "Nhặt SVC", "Not picked up", "Auto TTT", "AutoTTC", "ReMap", "Tàn sát map trống", "Auto Mua Thức Ăn", "TS khi hết MP", "Auto Reconnect", "Next Map Null Boss", "Săn TATL", "Hit Normal", "Hit Elitez", "Hit Chief", "Cộng tiềm năng", "Cộng kĩ năng", "Đánh theo nhóm", "Né PK", "Auto Cổ Lệnh", "Auto Mua Cổ Lệnh"};
            sda = "Use button < and > to change value";
            sea = "Touch to change value";
            sfa = "Distance is very far, Can not heal another people";
            sga = "Percent value is from 10 to 90";
            sha = new String[]{"Level 1", "Level 10", "Level 20", "Level 30", "Level 40", "Level 50", "Level 60", "Level 70"};
            sia = new String[]{"Level 1", "Level 2", "Level 3", "Level 4", "Level 5", "Level 6", "Level 7", "Level 8", "Level 9", "Level 10", "Level 11", "Level 12"};
            sja = "Account required password, input password to unlock.";
            ska = "Vitality";
            sla = "Name of mounts";
            sma = new String[]{"Upgrade essence by using 9 essences", "of the same kind or 3 common essences", "and stone level 11 or 3 rare essences and stone level 12."};
            sna = "Only common essence and rare essence";
            soa = "Only stone and essence to upgrade essence";
            spa = "Just only 1 stone to upgrade";
            sqa = "Need to use 3 rare essences and stone level 12 or 3 common essences and stone level 11";
            sra = "Have to use stone level 11 and 12";
            ssa = "Have to use essences of the same kind";
            sta = "Have to has 3 essences to Upgrade";
            sua = "Essences are excessive";
            sva = "This equipment can not Enhance";
            swa = "Not enough material";
            sxa = "This function is not available for this equipment";
            sya = "Save candy";
            sza = "Enhance level";
            taa = "Engine";
            tba = "Fuel";
            tca = "Give candy";
            tda = new String[]{"essence", "essence", "common essences", "rare essences"};
            tea = "Equipment enhanced to max level already";
         }

      }
   }

   public static String aaa(String var0, String var1) {
      return ex.aaa(var0, "#", var1);
   }

   public static void aba() {
   }

   static {
      aa.aaa(43);
      aba();
   }

   public static void aca() {
      aea = 0;
      afa = null;
      aga = null;
      aha = null;
      aia = null;
      aja = null;
      aka = null;
      ala = null;
      ama = null;
      ana = null;
      aoa = null;
      apa = null;
      aqa = null;
      ara = null;
      asa = null;
      ata = null;
      aua = null;
      ava = null;
      awa = null;
      axa = null;
      aya = null;
      aza = null;
      baa = null;
      bba = null;
      bca = null;
      bda = null;
      bea = null;
      bfa = null;
      bga = null;
      bha = null;
      bia = null;
      bja = null;
      bka = null;
      bla = null;
      bma = null;
      bna = null;
      boa = null;
      bpa = null;
      bqa = null;
      bra = null;
      bsa = null;
      bta = null;
      bua = null;
      bva = null;
      bwa = null;
      bxa = null;
      bya = null;
      bza = null;
      caa = null;
      cba = null;
      cca = null;
      cda = null;
      cea = null;
      cfa = null;
      cga = null;
      cha = null;
      cia = null;
      cja = null;
      cka = null;
      cla = null;
      cma = null;
      cna = null;
      coa = null;
      cpa = null;
      cqa = null;
      cra = null;
      csa = null;
      cta = null;
      cua = null;
      cva = null;
      cwa = null;
      cxa = null;
      cya = null;
      cza = null;
      daa = null;
      dba = null;
      dca = null;
      dda = null;
      dea = null;
      dfa = null;
      dga = null;
      dha = null;
      dia = null;
      dja = null;
      dka = null;
      dla = null;
      dma = null;
      dna = null;
      doa = null;
      dpa = null;
      dqa = null;
      dra = null;
      dsa = null;
      dta = null;
      dua = null;
      dva = null;
      dwa = null;
      dxa = null;
      dya = null;
      dza = null;
      eaa = null;
      eba = null;
      eca = null;
      eda = null;
      eea = null;
      efa = null;
      ega = null;
      eha = null;
      eia = null;
      eja = null;
      eka = null;
      ela = null;
      ema = null;
      ena = null;
      eoa = null;
      epa = null;
      eqa = null;
      era = null;
      esa = null;
      eta = null;
      eua = null;
      eva = null;
      ewa = null;
      exa = null;
      eya = null;
      eza = null;
      faa = null;
      fba = null;
      fca = null;
      fda = null;
      fea = null;
      ffa = null;
      fga = null;
      fha = null;
      fia = null;
      fja = null;
      fka = null;
      fla = null;
      fma = null;
      fna = null;
      foa = null;
      fpa = null;
      fqa = null;
      fra = null;
      fsa = null;
      fta = null;
      fua = null;
      fva = null;
      fwa = null;
      fxa = null;
      fya = null;
      fza = null;
      gaa = null;
      gba = null;
      gca = null;
      gda = null;
      gea = null;
      gfa = null;
      gga = null;
      gha = null;
      gia = null;
      gja = null;
      gka = null;
      gla = null;
      gma = null;
      gna = null;
      goa = null;
      gpa = null;
      gqa = null;
      gra = null;
      gsa = null;
      gta = null;
      gua = null;
      gva = null;
      gwa = null;
      gxa = null;
      gya = null;
      gza = null;
      haa = null;
      hba = null;
      hca = null;
      hda = null;
      hea = null;
      hfa = null;
      hga = null;
      hha = null;
      hia = null;
      hja = null;
      hka = null;
      hla = null;
      hma = null;
      hna = null;
      hoa = null;
      hpa = null;
      hqa = null;
      hra = null;
      hsa = null;
      hta = null;
      hua = null;
      hva = null;
      hwa = null;
      hxa = null;
      hya = null;
      hza = null;
      iaa = null;
      iba = null;
      ica = null;
      ida = null;
      iea = null;
      ifa = null;
      iga = null;
      iha = null;
      iia = null;
      ija = null;
      ika = null;
      ila = null;
      ima = null;
      ina = null;
      ioa = null;
      ipa = null;
      iqa = null;
      ira = null;
      isa = null;
      ita = null;
      iua = null;
      iva = null;
      iwa = null;
      ixa = null;
      iya = null;
      iza = null;
      jaa = null;
      jba = null;
      jca = null;
      jda = null;
      jea = null;
      jfa = null;
      jga = null;
      jha = null;
      jia = null;
      jja = null;
      jka = null;
      jla = null;
      jma = null;
      jna = null;
      joa = null;
      jpa = null;
      jqa = null;
      jra = null;
      jsa = null;
      jta = null;
      jua = null;
      jva = null;
      jwa = null;
      jxa = null;
      jya = null;
      jza = null;
      kaa = null;
      kba = null;
      kca = null;
      kda = null;
      kea = null;
      kfa = null;
      kga = null;
      kha = null;
      kia = null;
      kja = null;
      kka = null;
      kla = null;
      kma = null;
      kna = null;
      koa = null;
      kpa = null;
      kqa = null;
      kra = null;
      ksa = null;
      kta = null;
      kua = null;
      kva = null;
      kwa = null;
      kxa = null;
      kya = null;
      kza = null;
      laa = null;
      lba = null;
      lca = null;
      lda = null;
      lea = null;
      lfa = null;
      lga = null;
      lha = null;
      lia = null;
      lja = null;
      lka = null;
      lla = null;
      lma = null;
      lna = null;
      loa = null;
      lpa = null;
      lqa = null;
      lra = null;
      lsa = null;
      lta = null;
      lua = null;
      lva = null;
      lwa = null;
      lxa = null;
      lya = null;
      lza = null;
      maa = null;
      mba = null;
      mca = null;
      mda = null;
      mea = null;
      mfa = null;
      mga = null;
      mha = null;
      mia = null;
      mja = null;
      mka = null;
      mla = null;
      mma = null;
      mna = null;
      moa = null;
      mpa = null;
      mqa = null;
      mra = null;
      msa = null;
      mta = null;
      mua = null;
      mva = null;
      mwa = null;
      mxa = null;
      mya = null;
      mza = null;
      naa = null;
      nba = null;
      nca = null;
      nda = null;
      nea = null;
      nfa = null;
      nga = null;
      nha = null;
      nia = null;
      nja = null;
      nka = null;
      nla = null;
      nma = null;
      nna = null;
      noa = null;
      npa = null;
      nqa = null;
      nra = null;
      nsa = null;
      nta = null;
      nua = null;
      nva = null;
      nwa = null;
      nxa = null;
      nya = null;
      nza = null;
      oaa = null;
      oba = null;
      oca = null;
      oda = null;
      oea = null;
      ofa = null;
      oga = null;
      oha = null;
      oia = null;
      oja = null;
      oka = null;
      ola = null;
      oma = null;
      ona = null;
      ooa = null;
      opa = null;
      oqa = null;
      ora = null;
      osa = null;
      ota = null;
      oua = null;
      ova = null;
      owa = null;
      oxa = null;
      oya = null;
      oza = null;
      paa = null;
      pba = null;
      pca = null;
      pda = null;
      pea = null;
      pfa = null;
      pga = null;
      pha = null;
      pia = null;
      pja = null;
      pka = null;
      pla = null;
      pma = null;
      pna = null;
      poa = null;
      ppa = null;
      pqa = null;
      pra = null;
      psa = null;
      pta = null;
      pua = null;
      pva = null;
      pwa = null;
      pxa = null;
      pya = null;
      pza = null;
      qaa = null;
      qba = null;
      qca = null;
      qda = null;
      qea = null;
      qfa = null;
      qga = null;
      qha = null;
      qia = null;
      qja = null;
      qka = null;
      qla = null;
      qma = null;
      qna = null;
      qoa = null;
      qpa = null;
      qqa = null;
      qra = null;
      qsa = null;
      qta = null;
      qua = null;
      qva = null;
      qwa = null;
      qxa = null;
      qya = null;
      qza = null;
      raa = null;
      rba = null;
      rca = null;
      rda = null;
      rea = null;
      rfa = null;
      rga = null;
      rha = null;
      ria = null;
      rja = null;
      rka = null;
      rla = null;
      rma = null;
      rna = null;
      roa = null;
      rpa = null;
      rqa = null;
      rra = null;
      rsa = null;
      rta = null;
      rua = null;
      rva = null;
      rwa = null;
      rxa = null;
      rya = null;
      rza = null;
      saa = null;
      sba = null;
      sca = null;
      sda = null;
      sea = null;
      sfa = null;
      sga = null;
      sha = null;
      sia = null;
      sja = null;
      ska = null;
      sla = null;
      sma = null;
      sna = null;
      soa = null;
      spa = null;
      sqa = null;
      sra = null;
      ssa = null;
      sta = null;
      sua = null;
      sva = null;
      swa = null;
      sxa = null;
      sya = null;
      sza = null;
      taa = null;
      tba = null;
      tca = null;
      tda = null;
      tea = null;
      tfa = null;
      tga = null;
      tha = null;
      tia = null;
      tja = null;
      tka = null;
      tla = null;
      tma = null;
      tna = null;
   }
}
